### ISSUE TITLE
ModPatcher 1.10.2 not working

### ISSUE THREAD

**Issue by Slind14** [nallar/ModPatcher#13]
Hi @nallar,

it seems like that the ModPatcher 1.10.2 does not work (tested with and without Sponge). E.g. a simple patch like: 

https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/world/WorldEvents.java

```XML
<mods>
	<entitySpawnSpam>
		<class id="slimeknights.tconstruct.world.WorldEvents">
			<removeMethod>extraSlimeSpawn</removeMethod>
		</class>
	</entitySpawnSpam>
</mods>
```

results in:

```
Failed to patch slimeknights.tconstruct.world.WorldEvents in patch group slimeknights.tconstruct.world.WorldEvents.
javassist.NotFoundException: slimeknights.tconstruct.world.WorldEvents
	at javassist.ClassPool.get(ClassPool.java:452) ~[ClassPool.class:1.10.2-SNAPSHOT+Jenkins-b14.git-582f5a38fa4300b7b0df2615572147523772f3ad]
	at me.nallar.javapatcher.patcher.Patcher.patch(Patcher.java:210) [Patcher.class:1.10.2-SNAPSHOT+Jenkins-b14.git-582f5a38fa4300b7b0df2615572147523772f3ad]
	at me.nallar.modpatcher.ModPatcherTransformer.transformationHook(ModPatcherTransformer.java:86) [ModPatcherTransformer.class:1.10.2-SNAPSHOT+Jenkins-b14.git-582f5a38fa4300b7b0df2615572147523772f3ad]
	at me.nallar.modpatcher.ModPatcherTransformer$ClassTransformer.transform(ModPatcherTransformer.java:157) [ModPatcher-1.10.2-SNAPSHOT-lib.jar:1.10.2-SNAPSHOT+Jenkins-b14.git-582f5a38fa4300b7b0df2615572147523772f3ad]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_111]
	at slimeknights.tconstruct.world.TinkerWorld.postInit(TinkerWorld.java:122) [TinkerWorld.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at slimeknights.mantle.pulsar.flightpath.Flightpath.post(Flightpath.java:89) [Flightpath.class:?]
	at slimeknights.mantle.pulsar.control.PulseManager.propagateEvent(PulseManager.java:203) [PulseManager.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:800) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by LunNova** [comment]
TickProfiler 1.10.2 works using ModPatcher. Are patches on net.minecraft classes also broken for you?

**Comment by Slind14** [comment]
Yes TickProfiler works.

I enabled the example patch which  results in: 

```java.lang.RuntimeException: Method not found: getBlock() was not found in net.minecraft.world.World
	at me.nallar.javapatcher.mappings.MethodDescription.inClass(MethodDescription.java:173) ~[MethodDescription.class:1.10.2-SNAPSHOT+Jenkins-b14.git-582f5a38fa4300b7b0df2615572147523772f3ad]
	at me.nallar.javapatcher.patcher.Patcher$PatchMethodDescriptor.run(Patcher.java:390) [Patcher$PatchMethodDescriptor.class:1.10.2-SNAPSHOT+Jenkins-b14.git-582f5a38fa4300b7b0df2615572147523772f3ad]
	at me.nallar.javapatcher.patcher.Patcher$ClassPatchDescriptor.runPatches(Patcher.java:522) [Patcher$ClassPatchDescriptor.class:1.10.2-SNAPSHOT+Jenkins-b14.git-582f5a38fa4300b7b0df2615572147523772f3ad]
	at me.nallar.javapatcher.patcher.Patcher.patch(Patcher.java:212) [Patcher.class:1.10.2-SNAPSHOT+Jenkins-b14.git-582f5a38fa4300b7b0df2615572147523772f3ad]
	at me.nallar.modpatcher.ModPatcherTransformer.transformationHook(ModPatcherTransformer.java:86) [ModPatcherTransformer.class:1.10.2-SNAPSHOT+Jenkins-b14.git-582f5a38fa4300b7b0df2615572147523772f3ad]
	at me.nallar.modpatcher.ModPatcherTransformer$ClassTransformer.transform(ModPatcherTransformer.java:157) [ModPatcher-1.10.2-SNAPSHOT-lib.jar:1.10.2-SNAPSHOT+Jenkins-b14.git-582f5a38fa4300b7b0df2615572147523772f3ad]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_111]
	at net.minecraft.client.main.Main.main(SourceFile:39) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

So it finds the class in that case.

**Comment by Slind14** [comment]
Do you have time to look into it soon, or should I fall back to more serious ways?

**Comment by LunNova** [comment]
I might get to it soon, might not. If it's time critical you'll need to patch the jar manually for now.

**Comment by LunNova** [comment]
Oops... Forgot about this.

https://github.com/nallar/ModPatcher/blob/1.11/src/main/java/me/nallar/modpatcher/LaunchClassLoaderUtil.java#L152

**Comment by LunNova** [comment]
Use the latest version (delete ModPatcher.jlib from mods folder so it grabs the latest one), set -Dnallar.LaunchClassLoaderUtil.allowPatchingAllClasses=true. Will need a better fix later, preventing javassist loading classes it didn't need to improved server start times when using ModPatcher.

**Comment by Slind14** [comment]
ahh, thank you. How bad is that startup time impact?
btw. the build server isn't picking up the new commit

**Comment by LunNova** [comment]
Made some changes, this is no longer necessary. Startup time impact was a few % extra classloading time + extra memory usage.

**Comment by Slind14** [comment]
ok, thank you
