### ISSUE TITLE
Incompatible with Mixin 0.8

### ISSUE THREAD

**Issue by clienthax** [nallar/ModPatcher#20]
https://github.com/MinimallyCorrect/ModPatcher/blob/1.11.2/src/main/java/org/minimallycorrect/modpatcher/api/tweaker/ModPatcherTweaker2.java#L24
Needs to be updated to use 
```
MixinService.getService().getTransformerProvider().addTransformerExclusion(...)
```
however this may not be needed anymore as it also shouldn't be required because transformer exclusions are only for re-entrant transformers

```
[15:17:42] [main/WARN] [ModPatcher]: Failed to add mixin transformer exclusion for our transformer
java.lang.NoSuchFieldException: excludeTransformers
	at java.lang.Class.getDeclaredField(Class.java:820) ~[?:1.8.0_212]
	at org.minimallycorrect.modpatcher.api.tweaker.ModPatcherTweaker2.inject(ModPatcherTweaker2.java:24) [ModPatcher-1.12-SNAPSHOT.jar:1.12-SNAPSHOT+Jenkins-b5.git-24e3b38023c281ee5d327595ecaea7f37f198dfc]
	at org.minimallycorrect.modpatcher.api.tweaker.ModPatcherTweaker2.getLaunchArguments(ModPatcherTweaker2.java:52) [ModPatcher-1.12-SNAPSHOT.jar:1.12-SNAPSHOT+Jenkins-b5.git-24e3b38023c281ee5d327595ecaea7f37f198dfc]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70) [forge-1.12.2-14.23.5.2847-universal.jar:?]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34) [forge-1.12.2-14.23.5.2847-universal.jar:?]
[15:17:42] [main/INFO] [ModPatcher]: Transformers: [net.minecraftforge.fml.common.asm.transformers.PatchingTransformer@76b777bd, org.spongepowered.asm.mixin.transformer.Proxy@73a88b5b, TransformerWrapper(net.minecraftforge.fml.common.asm.transformers.SideTransformer, FMLCorePlugin), TransformerWrapper(net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer, FMLCorePlugin), TransformerWrapper(net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer, FMLCorePlugin), TransformerWrapper(net.minecraftforge.fml.common.asm.transformers.SoundEngineFixTransformer, FMLCorePlugin), TransformerWrapper(micdoodle8.mods.miccore.MicdoodleTransformer, MicdoodlePlugin), TransformerWrapper(org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer, SpongeCoremod), TransformerWrapper(org.dimdev.jeid.JEIDTransformer, JustEnoughIDs Extension Plugin), codechicken.asm.internal.SnifferTransformer@23df124a, TransformerWrapper(openmods.core.OpenModsClassTransformer, OpenModsCorePlugin), net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer@18a6b0b6, net.minecraftforge.fml.common.asm.transformers.AccessTransformer@4e38176e, pl.asie.foamfix.coremod.FoamFixAT@fd67e065, micdoodle8.mods.miccore.MicdoodleAccessTransformer@ed32a02a, org.spongepowered.mod.asm.transformer.SpongeAccessTransformer@cbd21d07, net.minecraftforge.fml.common.asm.transformers.ModAccessTransformer@76cb0574, net.minecraftforge.fml.common.asm.transformers.ItemStackTransformer@a1297526, net.minecraftforge.fml.common.asm.transformers.ItemBlockTransformer@54b074fa, net.minecraftforge.fml.common.asm.transformers.ItemBlockSpecialTransformer@e02f02c1, net.minecraftforge.fml.common.asm.transformers.PotionEffectTransformer@6abb5454, org.spongepowered.asm.mixin.transformer.Proxy@7af980a8, TransformerWrapper(com.chocohead.biab.BornInABarn, Born in a Barn), TransformerWrapper(pl.asie.foamfix.coremod.FoamFixTransformer, Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.)), TransformerWrapper(li.cil.oc.common.asm.ClassTransformer, TransformerLoader), TransformerWrapper(mekanism.coremod.KeybindingMigrationHelper, MekanismCoremod), TransformerWrapper(com.therandomlabs.randompatches.core.RPTransformer, RandomPatches), TransformerWrapper(com.enderio.core.common.transform.EnderCoreTransformer, EnderCorePlugin), TransformerWrapper(com.enderio.core.common.transform.SimpleMixinPatcher, EnderCorePlugin), net.minecraftforge.fml.common.asm.transformers.TerminalTransformer@e1e21014, org.spongepowered.asm.mixin.transformer.Proxy@c642cd2c, sampler.core.Transformer@5299fd27, org.minimallycorrect.modpatcher.api.ModPatcherTransformer$ClassTransformer@34014aa8]

```

**Comment by LunNova** [comment]
thanks clienthax. Our transformer is kinda reentrant, it needs metadata, although we can fake it mostly by storing just the class/method/field names stored for javassist to use instead.

Currently changing some things around and were planning to drop support for the old XML style patches, which are what made a lot of the messing around necessary.

Are you still using those?

**Comment by clienthax** [comment]
I only ran into this while looking into why my server wasnt loading up and noticed the error (i assume its being used by tickprofiler) :D

**Comment by LunNova** [comment]
Okay, cool. Hoping to have a new version of TickProfiler out soon which doesn't use the old patcher, will make sure that works with Mixin 0.8.

Is there a pack you're using we can test with?

**Comment by clienthax** [comment]
Im running this currently https://www.technicpack.net/modpack/the-1122-pack.1406454

**Comment by LunNova** [comment]
Fixed by @LXGaming's patch. Thanks!
